// Mocks generated by Mockito 5.4.6 from annotations
// in hamma/test/sftp_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;
import 'dart:typed_data' as _i15;

import 'package:dartssh2/src/http/http_client.dart' as _i9;
import 'package:dartssh2/src/sftp/sftp_client.dart' as _i2;
import 'package:dartssh2/src/sftp/sftp_file_attrs.dart' as _i3;
import 'package:dartssh2/src/sftp/sftp_file_open_mode.dart' as _i11;
import 'package:dartssh2/src/sftp/sftp_name.dart' as _i12;
import 'package:dartssh2/src/sftp/sftp_statvfs.dart' as _i4;
import 'package:dartssh2/src/socket/ssh_socket.dart' as _i5;
import 'package:dartssh2/src/ssh_algorithm.dart' as _i6;
import 'package:dartssh2/src/ssh_client.dart' as _i14;
import 'package:dartssh2/src/ssh_forward.dart' as _i7;
import 'package:dartssh2/src/ssh_session.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i13;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSftpHandsake_0 extends _i1.SmartFake implements _i2.SftpHandsake {
  _FakeSftpHandsake_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSftpFileAttrs_1 extends _i1.SmartFake implements _i3.SftpFileAttrs {
  _FakeSftpFileAttrs_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSftpFile_2 extends _i1.SmartFake implements _i2.SftpFile {
  _FakeSftpFile_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSftpStatVfs_3 extends _i1.SmartFake implements _i4.SftpStatVfs {
  _FakeSftpStatVfs_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSSHSocket_4 extends _i1.SmartFake implements _i5.SSHSocket {
  _FakeSSHSocket_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSSHAlgorithms_5 extends _i1.SmartFake implements _i6.SSHAlgorithms {
  _FakeSSHAlgorithms_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSSHForwardChannel_6 extends _i1.SmartFake
    implements _i7.SSHForwardChannel {
  _FakeSSHForwardChannel_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSSHSession_7 extends _i1.SmartFake implements _i8.SSHSession {
  _FakeSSHSession_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSftpClient_8 extends _i1.SmartFake implements _i2.SftpClient {
  _FakeSftpClient_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSSHHttpClient_9 extends _i1.SmartFake implements _i9.SSHHttpClient {
  _FakeSSHHttpClient_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SftpClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockSftpClient extends _i1.Mock implements _i2.SftpClient {
  MockSftpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i2.SftpHandsake> get handshake =>
      (super.noSuchMethod(
            Invocation.getter(#handshake),
            returnValue: _i10.Future<_i2.SftpHandsake>.value(
              _FakeSftpHandsake_0(this, Invocation.getter(#handshake)),
            ),
          )
          as _i10.Future<_i2.SftpHandsake>);

  @override
  _i10.Future<_i3.SftpFileAttrs> stat(
    String? path, {
    bool? followLink = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#stat, [path], {#followLink: followLink}),
            returnValue: _i10.Future<_i3.SftpFileAttrs>.value(
              _FakeSftpFileAttrs_1(
                this,
                Invocation.method(#stat, [path], {#followLink: followLink}),
              ),
            ),
          )
          as _i10.Future<_i3.SftpFileAttrs>);

  @override
  _i10.Future<void> setStat(String? path, _i3.SftpFileAttrs? attrs) =>
      (super.noSuchMethod(
            Invocation.method(#setStat, [path, attrs]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<_i2.SftpFile> open(
    String? path, {
    _i11.SftpFileOpenMode? mode = _i11.SftpFileOpenMode.read,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#open, [path], {#mode: mode}),
            returnValue: _i10.Future<_i2.SftpFile>.value(
              _FakeSftpFile_2(
                this,
                Invocation.method(#open, [path], {#mode: mode}),
              ),
            ),
          )
          as _i10.Future<_i2.SftpFile>);

  @override
  _i10.Stream<List<_i12.SftpName>> readdir(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#readdir, [path]),
            returnValue: _i10.Stream<List<_i12.SftpName>>.empty(),
          )
          as _i10.Stream<List<_i12.SftpName>>);

  @override
  _i10.Future<List<_i12.SftpName>> listdir(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#listdir, [path]),
            returnValue: _i10.Future<List<_i12.SftpName>>.value(
              <_i12.SftpName>[],
            ),
          )
          as _i10.Future<List<_i12.SftpName>>);

  @override
  _i10.Future<void> remove(String? filename) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [filename]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> mkdir(String? path, [_i3.SftpFileAttrs? attrs]) =>
      (super.noSuchMethod(
            Invocation.method(#mkdir, [path, attrs]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> rmdir(String? dirname) =>
      (super.noSuchMethod(
            Invocation.method(#rmdir, [dirname]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<String> absolute(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#absolute, [path]),
            returnValue: _i10.Future<String>.value(
              _i13.dummyValue<String>(
                this,
                Invocation.method(#absolute, [path]),
              ),
            ),
          )
          as _i10.Future<String>);

  @override
  _i10.Future<void> rename(String? oldPath, String? newPath) =>
      (super.noSuchMethod(
            Invocation.method(#rename, [oldPath, newPath]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<String> readlink(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#readlink, [path]),
            returnValue: _i10.Future<String>.value(
              _i13.dummyValue<String>(
                this,
                Invocation.method(#readlink, [path]),
              ),
            ),
          )
          as _i10.Future<String>);

  @override
  _i10.Future<void> link(String? linkPath, String? targetPath) =>
      (super.noSuchMethod(
            Invocation.method(#link, [linkPath, targetPath]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<_i4.SftpStatVfs> statvfs(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#statvfs, [path]),
            returnValue: _i10.Future<_i4.SftpStatVfs>.value(
              _FakeSftpStatVfs_3(this, Invocation.method(#statvfs, [path])),
            ),
          )
          as _i10.Future<_i4.SftpStatVfs>);

  @override
  void close() => super.noSuchMethod(
    Invocation.method(#close, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [SSHClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockSSHClient extends _i1.Mock implements _i14.SSHClient {
  MockSSHClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.SSHSocket get socket =>
      (super.noSuchMethod(
            Invocation.getter(#socket),
            returnValue: _FakeSSHSocket_4(this, Invocation.getter(#socket)),
          )
          as _i5.SSHSocket);

  @override
  String get username =>
      (super.noSuchMethod(
            Invocation.getter(#username),
            returnValue: _i13.dummyValue<String>(
              this,
              Invocation.getter(#username),
            ),
          )
          as String);

  @override
  _i6.SSHAlgorithms get algorithms =>
      (super.noSuchMethod(
            Invocation.getter(#algorithms),
            returnValue: _FakeSSHAlgorithms_5(
              this,
              Invocation.getter(#algorithms),
            ),
          )
          as _i6.SSHAlgorithms);

  @override
  bool get disableHostkeyVerification =>
      (super.noSuchMethod(
            Invocation.getter(#disableHostkeyVerification),
            returnValue: false,
          )
          as bool);

  @override
  _i10.Future<void> get done =>
      (super.noSuchMethod(
            Invocation.getter(#done),
            returnValue: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i10.Future<void> get authenticated =>
      (super.noSuchMethod(
            Invocation.getter(#authenticated),
            returnValue: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<_i14.SSHRemoteForward?> forwardRemote({
    String? host,
    int? port,
    _i14.SSHRemoteConnectionFilter? filter,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#forwardRemote, [], {
              #host: host,
              #port: port,
              #filter: filter,
            }),
            returnValue: _i10.Future<_i14.SSHRemoteForward?>.value(),
          )
          as _i10.Future<_i14.SSHRemoteForward?>);

  @override
  _i10.Future<bool> cancelForwardRemote(_i14.SSHRemoteForward? forward) =>
      (super.noSuchMethod(
            Invocation.method(#cancelForwardRemote, [forward]),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<_i7.SSHForwardChannel> forwardLocal(
    String? remoteHost,
    int? remotePort, {
    String? localHost = 'localhost',
    int? localPort = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #forwardLocal,
              [remoteHost, remotePort],
              {#localHost: localHost, #localPort: localPort},
            ),
            returnValue: _i10.Future<_i7.SSHForwardChannel>.value(
              _FakeSSHForwardChannel_6(
                this,
                Invocation.method(
                  #forwardLocal,
                  [remoteHost, remotePort],
                  {#localHost: localHost, #localPort: localPort},
                ),
              ),
            ),
          )
          as _i10.Future<_i7.SSHForwardChannel>);

  @override
  _i10.Future<_i7.SSHForwardChannel> forwardLocalUnix(
    String? remoteSocketPath,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#forwardLocalUnix, [remoteSocketPath]),
            returnValue: _i10.Future<_i7.SSHForwardChannel>.value(
              _FakeSSHForwardChannel_6(
                this,
                Invocation.method(#forwardLocalUnix, [remoteSocketPath]),
              ),
            ),
          )
          as _i10.Future<_i7.SSHForwardChannel>);

  @override
  _i10.Future<_i8.SSHSession> execute(
    String? command, {
    _i14.SSHPtyConfig? pty,
    Map<String, String>? environment,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #execute,
              [command],
              {#pty: pty, #environment: environment},
            ),
            returnValue: _i10.Future<_i8.SSHSession>.value(
              _FakeSSHSession_7(
                this,
                Invocation.method(
                  #execute,
                  [command],
                  {#pty: pty, #environment: environment},
                ),
              ),
            ),
          )
          as _i10.Future<_i8.SSHSession>);

  @override
  _i10.Future<_i8.SSHSession> shell({
    _i14.SSHPtyConfig? pty = const _i14.SSHPtyConfig(),
    Map<String, String>? environment,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#shell, [], {
              #pty: pty,
              #environment: environment,
            }),
            returnValue: _i10.Future<_i8.SSHSession>.value(
              _FakeSSHSession_7(
                this,
                Invocation.method(#shell, [], {
                  #pty: pty,
                  #environment: environment,
                }),
              ),
            ),
          )
          as _i10.Future<_i8.SSHSession>);

  @override
  _i10.Future<void> subsystem(String? subsystem) =>
      (super.noSuchMethod(
            Invocation.method(#subsystem, [subsystem]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<_i2.SftpClient> sftp() =>
      (super.noSuchMethod(
            Invocation.method(#sftp, []),
            returnValue: _i10.Future<_i2.SftpClient>.value(
              _FakeSftpClient_8(this, Invocation.method(#sftp, [])),
            ),
          )
          as _i10.Future<_i2.SftpClient>);

  @override
  _i9.SSHHttpClient httpClient() =>
      (super.noSuchMethod(
            Invocation.method(#httpClient, []),
            returnValue: _FakeSSHHttpClient_9(
              this,
              Invocation.method(#httpClient, []),
            ),
          )
          as _i9.SSHHttpClient);

  @override
  _i10.Future<_i15.Uint8List> run(
    String? command, {
    bool? runInPty = false,
    bool? stdout = true,
    bool? stderr = true,
    Map<String, String>? environment,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #run,
              [command],
              {
                #runInPty: runInPty,
                #stdout: stdout,
                #stderr: stderr,
                #environment: environment,
              },
            ),
            returnValue: _i10.Future<_i15.Uint8List>.value(_i15.Uint8List(0)),
          )
          as _i10.Future<_i15.Uint8List>);

  @override
  _i10.Future<void> ping() =>
      (super.noSuchMethod(
            Invocation.method(#ping, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  void close() => super.noSuchMethod(
    Invocation.method(#close, []),
    returnValueForMissingStub: null,
  );

  @override
  void handlePacket(_i15.Uint8List? packet) => super.noSuchMethod(
    Invocation.method(#handlePacket, [packet]),
    returnValueForMissingStub: null,
  );
}
